// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogthkjugrlvvzcfortcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ndGhranVncmx2dnpjZm9ydGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDU5NzYsImV4cCI6MjA2ODM4MTk3Nn0.jrdk2T9CU5498wElngl5PWjcN3inohYp7vTgCl7isqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});